[workspace]
members = [
	"cpacfinfo",
	"pv",
	"pv_core",
	"pvapconfig",
	"pvattest",
	"pvsecret",
	"utils",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
rust-version = "1.75.0"

[profile.release]
lto = true
